<?xml version="1.0" encoding="UTF-8"?>
<customMapSource>
  <!-- https://github.com/pp-gps-p/Aland-ortofoton-i-Guru-Maps -->
  <!-- This proxy will be available until September 2025 -->
  <name>Mariehamn orto 1982</name>
  <url>http://52.57.84.58:8080/wmts/aland1982_EPSG3857/webmercator/{$z}/{$x}/{$y}.png</url>
  <minZoom>12</minZoom>
  <maxZoom>18</maxZoom>
  <tileSize>256</tileSize>
</customMapSource>
